name: cast
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - torchvision=0.14.1
  - pip:
    - opencv-contrib-python
    - timm==0.4.12
    - setuptools==58.0.4
    - tensorboard
    - hostlist
    - scikit-image
    - mmcv==1.3.8
    - mmsegmentation==0.14.1
    - einops
    - easydict==1.9
    - pyyaml==5.3
    - tensorboardX
